#server:
#  port: 5000
spring:
  profiles:
    active: test #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
      max-request-size: 100MB
#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml
logging:
  level:
    cn.no7player.mapper: DEBUG

