package cn.no7player.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Created by liying
 * Date 2020-08-10
 */


public class UserExcel implements Serializable {

    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
}
